FROM arm64v8/python:3-buster
COPY qemu-aarch64-static /usr/bin/

WORKDIR /usr/src/app

COPY rf_receiver.py /.
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Define default command
ENTRYPOINT ["python", "./rf_receiver.py"]