FROM arm32v6/python:3-alpine
COPY qemu-arm-static /usr/bin/

WORKDIR /usr/src/app

COPY rf_receiver.py /.
COPY requirements.txt ./

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Define default command
ENTRYPOINT ["python", "./rf_receiver.py"]